### ISSUE TITLE
why does easyBPY provide duplicate functions?

### ISSUE THREAD

**Issue by hannesdelbeke** [curtisjamesholt/EasyBPY#12]
example:

```python
def set_render_engine_cycles():
    set_render_engine_to_cycles()

def set_render_engine_eevee():
    set_render_engine_to_eevee()
```

why provide set_render_engine_cycles, if there is set_render_engine_to_cycles
it goes against [the zen of Python](https://peps.python.org/pep-0020/) `There should be one-- and preferably only one --obvious way to do it`

**Comment by curtisjamesholt** [comment]
Convenience functions for language expression.
I don't want to have to remember whether there's a 'to' in the function name or not, so there is both.
If you don't like it, you can remove it.
