### ISSUE TITLE
create primitive object return the active one would be right reference , isn't it ?

### ISSUE THREAD

**Issue by lightspread** [curtisjamesholt/EasyBPY#4]
def create_cube():
    bpy.ops.mesh.primitive_cube_add()
    return bpy.data.objects["Cube"]

def create_cube():
    bpy.ops.mesh.primitive_cube_add()
    return bpy.context.active_object

**Comment by curtisjamesholt** [comment]
Yep, changed it, will be in 0.0.4 (sometime today). 👍
