### ISSUE TITLE
Returning so() as a fallback

### ISSUE THREAD

**Issue by AlexanderPavlenko** [curtisjamesholt/EasyBPY#6]
Hello! Thanks for this code, I like the idea.
There is one thing which caught my attention:
`get_object()` is not equal to `so()`, but `get_object('NameWithTypo')` returns `so()`.
I think in order to optimize UX every name string should be considered mistyped and the unexpected results will cause confusion until the typo is noticed.
`get_object(None)` returns `so()` too, but if `ref` argument contains `None` isn't it [a mistake](https://www.infoq.com/presentations/Null-References-The-Billion-Dollar-Mistake-Tony-Hoare/) as well?

**Comment by curtisjamesholt** [comment]
I agree, changed for 0.0.6.
