### ISSUE TITLE
arguments better than 4 functions

### ISSUE THREAD

**Issue by extorc** [curtisjamesholt/EasyBPY#8]
For example in the recent commit u have done , u have fluid type
so u have done `set_fluid_type_none` ,`set_fluid_type_domain` and so on
wont it be better and more effitient for u to do `set_fluid_type(type):` and then pass type into command inside
removing 4 functions for 1.
The reason for me suggesting this is that a person who knows a little bit of programming expects things to be this way
even if u want to keep this easy
u can just add an alternative 5th functions to support mainstream workflow also
Similarly instead of having <br>
`flow_type_set_smoke`
` flow_type_set_fire`
` flow_type_set_fire_smoke`
 `flow_type_set_fluid`
 u can have `set_flow_type(type)`

**Comment by curtisjamesholt** [comment]
Yep, I agree with u (you).
These are not my functions but I can clean that up in the future.
